import yaml

config = {
    'model': {
        'aya:35b': {'hf': 'CohereForAI/aya-23-35B',
                    'old_dir': 'aya', 'old_fn': 'aya_35b'},
        'aya': {'hf': 'CohereForAI/aya-23-8B',
                'old_dir': 'aya', 'old_fn': 'aya_8b'},
        'aya-expanse': {'hf': 'CohereForAI/aya-expanse-8b'},
        'command-r': {'hf': 'CohereForAI/c4ai-command-r-v01'},
        'gemma': {'hf': 'google/gemma-7b-it',
                  'old_dir': 'gemma', 'old_fn': 'gemma'},
        'gemma2': {'hf': 'google/gemma-2-9b-it',
                   'old_dir': 'gemma2', 'old_fn': 'gemma2_9b'},
        'gemma2:27b': {'hf': 'google/gemma-2-27b-it'},
        'granite3-dense': {'hf': 'ibm-granite/granite-3.0-2b-instruct'},
        'granite3-dense:8b': {'hf': 'ibm-granite/granite-3.0-8b-instruct'},
        'llama3': {'hf': 'meta-llama/Meta-Llama-3-8B-Instruct',
                   'old_dir': 'llama3', 'old_fn': 'llama3_8b'},
        'llama3:70b-instruct-q2_K': {'hf': 'meta-llama/Meta-Llama-3-70B-Instruct',
                                     'old_dir': 'llama3', 'old_fn': 'llama3_70b'},
        'llama3.1': {'hf': 'meta-llama/Llama-3.1-8B-Instruct',
                     'old_dir': 'llama3_1', 'old_fn': 'llama3.1_8b'},
        'llama3.1:70b-instruct-q2_K': {'hf': 'meta-llama/Llama-3.1-70B-Instruct'},
        'llama3.2': {'hf': 'meta-llama/Llama-3.2-3B-Instruct'},
        'mistral': {'hf': 'mistralai/Mistral-7B-Instruct-v0.3',
                    'old_dir': 'mistral', 'old_fn': 'mistral'},
        'mistral-nemo': {'hf': 'mistralai/Mistral-Nemo-Instruct-2407',
                         'old_dir': 'mistral_nemo', 'old_fn': 'mistral_nemo'},
        'mistral-small': {'hf': 'mistralai/Mistral-Small-Instruct-2409'},
        'mixtral': {'hf': 'mistralai/Mixtral-8x7B-Instruct-v0.1',
                    'old_dir': 'mixtral', 'old_fn': 'mixtral_8x7b'},
        'nemotron-mini': {'hf': 'nvidia/Nemotron-Mini-4B-Instruct'},
        'phi3': {'hf': 'microsoft/Phi-3-mini-4k-instruct',
                 'old_dir': 'phi3', 'old_fn': 'phi3_3.8b'},
        'phi3:14b': {'hf': 'microsoft/Phi-3-medium-4k-instruct',
                     'old_dir': 'phi3', 'old_fn': 'phi3_3.8b'},
        'phi3.5': {'hf': 'microsoft/Phi-3.5-mini-instruct'},
        'qwen2': {'hf': 'Qwen/Qwen2-7B-Instruct',
                  'old_dir': 'qwen2', 'old_fn': 'qwen2_7b'},
        'qwen2:72b-instruct-q2_K': {'hf': 'Qwen/Qwen2-72B-Instruct'},
        'qwen2.5': {'hf': 'Qwen/Qwen2.5-7B-Instruct'},
        'qwen2.5:14b': {'hf': 'Qwen/Qwen2.5-14B-Instruct'},
        'qwen2.5:32b': {'hf': 'Qwen/Qwen2.5-32B-Instruct'},
        'qwen2.5:72b': {'hf': 'Qwen/Qwen2.5-72B-Instruct'},
    },
    'prompt': {
        'ara': 'prompts/ara_prompt.txt',
        'lat': 'prompts/lat_prompt.txt',
        'occ': 'prompts/occ_prompt.txt',
        'ofr': 'prompts/ofr_prompt.txt',
    }
}

with open('translate_config.yaml', 'w') as f:
    yaml.dump(config, f)
